name: polls_for_devs
description: Polls for Devs App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http:

dev_dependencies:
  faker: ^1.3.0
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mockito: ^5.0.0
  test: ^1.16.5

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android.png
  image_path_ios: lib/ui/assets/icon/ios.png
  adaptive_icon_background: lib/ui/assets/icon/background.png
  adaptive_icon_foreground: lib/ui/assets/icon/foreground.png
